language: cpp

sudo: false

compiler:
    - gcc


before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && ./factorial_tests/basic_tests/runBasicFactorialTests

os:
    - linux

env:
  global:
  - LANG="en_US.UTF-8"